[package]
name = "tinycache"
version = "0.1.0"
edition = "2021"
description = "minimal, simple file cache with binary serialization"

[dependencies]
bincode = "1.3.3"
serde = { version = "1.0.166", features = ["derive"] }
tracing = "0.1.37"
sha1 = "0.10.5"